[build]
  command = "npm install && npx gulp buildRelease"
  publish = "."

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.b3dm"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.pnts"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.i3dm"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.cmpt"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
